[package]
name = "remote-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
ignore = "0.4"
notify = { version = "8.0.0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde-binary = "0.5.0"
serde_json = "1.0.140"
